export const itemData = [
    {
      name: "Bulbasaur",
      type: "Grass",
      stage:"1",
      evolutions:"yes",
      weaknesses:"Fire",
      hp: "260",
    },
    {
        name: "Charmander",
        type: "Fire",
        stage:"1",
        evolutions:"yes",
        weaknesses:"Water",
        hp: "260",
    },
    {
        name: "Squirtle",
        type: "Water",
        stage:"1",
        evolutions:"yes",
        weaknesses:"Grass",
        hp: "260",
    },
    {
        name: "Caterpie",
        type: "Bug",
        stage:"1",
        evolutions:"yes",
        weaknesses:"Fire",
        hp: "260",
    },
    {
        name: "Weedle",
        type: "Bug",
        stage:"1",
        evolutions:"yes",
        weaknesses:"Fire",
        hp: "260",
    },
    {
        name: "Pidgey",
        type: "Normal",
        stage:"1",
        evolutions:"yes",
        weaknesses:"Electric",
        hp: "260",
    },
  ];